feign:
  hystrix:
    enabled: true

weather-station:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    ServerListRefreshInterval: 1000
    OkToRetryOnAllOperations: yes

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000