endpoints:
  shutdown:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false

spring:
  cloud:
    discovery:
      client:
        composite-indicator.enabled: false

weather:
  temperature: 20
  humidity: 0.5

sensors:
  min-temperature: -30
  max-temperature: 30